### ISSUE TITLE
Can't access SQL Persistence scripts when running inside an Azure Function

### ISSUE THREAD

**Issue by jenspettersson** [Particular/NServiceBus.AzureFunctions.InProcess.ServiceBus#125]
We're trying to use SQL Persistence for sagas and with outbox enabled but the installer can't access the SQL scripts. It seems it tries to locate the generated SQL script files from the Azure Functions Core Tools directory (or similar) and they aren't there (as they're placed inside the `bin\Debug\netcoreapp3.1\NServiceBus.Persistence.Sql\MsSqlServer` folder).

Different locations based on how we start the endpoint:

Visual Studio:
```
System.Private.CoreLib: Exception while executing function: Core. NServiceBus.Persistence.Sql: Expected 'C:\Program Files\Microsoft\Azure Functions Core Tools\NServiceBus.Persistence.Sql\MsSqlServer\Outbox_Create.sql' to exist. It is possible it was not deployed with the endpoint.
```

Rider 2020.3:
```
System.Private.CoreLib: Exception while executing function: Core. NServiceBus.Persistence.Sql: Expected 'C:\Users\username\AppData\Roaming\JetBrains\Rider2020.3\azure-functions-coretools\3.0.3233\NServiceBus.Persistence.Sql\MsSqlServer\Outbox_Create.sql' to exist. It is possible it was not deployed with the endpoint.
```

func start from the CLI:
```
System.Private.CoreLib: Exception while executing function: Core. NServiceBus.Persistence.Sql: Expected 'C:\Users\username\AppData\Local\AzureFunctionsTools\Releases\3.18.0\cli_x64\NServiceBus.Persistence.Sql\MsSqlServer\Outbox_Create.sql' to exist. It is possible it was not deployed with the endpoint.
```

Do you have any ideas on how to get this to work when running as an Azure Function?

**Comment by SeanFeldman** [comment]
Also discussed in the following [Discourse thread](https://discuss.particular.net/t/sql-persistence-scripts-and-azure-functions/2267).

**Comment by SeanFeldman** [comment]
A [workaround](https://discuss.particular.net/t/sql-persistence-scripts-and-azure-functions/2267/4) is to use `builder.GetContext().ApplicationRootPath` in the `UseNServiceBus` method in the following way:

```c#
var configuration = new ServiceBusTriggeredEndpointConfiguration(
  AzureServiceBusTriggerFunction.EndpointName, "AzureServiceBus_ConnectionString");

var settings = configuration.AdvancedConfiguration.GetSettings();
settings.Set("SqlPersistence.ScriptDirectory", builder.GetContext().ApplicationRootPath); // the base path where SQL scripts will be found
```

**Comment by SeanFeldman** [comment]
This issue is not directly related to Azure Functions. With the [workaround](https://github.com/Particular/NServiceBus.AzureFunctions.InProcess.ServiceBus/issues/125#issuecomment-783952248) to unblock anyone who needs to specify scripts location, closing this issue.
