### ISSUE TITLE
Support Functions with isolated worker

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureFunctions.InProcess.ServiceBus#148]
- The Preview package `NServiceBus.AzureFunctions.ServiceBus` will be renamed to `NServiceBus.AzureFunctions.InProcess.ServiceBus` and will be made generally available first. The package will target `Microsoft.NET.Sdk.Functions` SDK and NServiceBus version 7. Just as the preview was to allow those using it in production to continue w/o any disruption to their production environment.
- The package will receive the necessary updates (dependencies, NServiceBus major version, etc) as necessary.
- A future **separate package** `NServiceBus.AzureFunctions.ServiceBus` targeting `Microsoft.Azure.Functions.Worker` SDK will follow later, providing support to the Isolated Worker and.NET5/6.

**Comment by seankearney** [comment]
We are currently on Azure Functions v3 using EF Core 3 and we'd like to upgrade our .NET Core to v5. However, EF Core v5 won't be supported with in-proc functions until .NET 6 is supported. For us to move to EF Core 5 we need to move to Functions isolated worker and to do that we require this.

**Comment by RobCloudlr** [comment]
We totally need this as well for EF Core v5. If you have preview nugets, we are also willing to test!

**Comment by SeanFeldman** [comment]
👍 for this from the other side 😀

**Comment by kevinroconnor** [comment]
We are also moving to .NET 5/6, and would be glad to help test as well!

**Comment by mycr4ft** [comment]
Same over here :)

**Comment by timbussmann** [comment]
We have implemented support for the isolated worker hosting model via [NServiceBus.AzureFunctions.Worker.ServiceBus](https://github.com/Particular/NServiceBus.AzureFunctions.Worker.ServiceBus). The packages are currently available as pre-release packages on our myget feed but should be released as RTM in the following days. We have docs and samples available here: 
* https://docs.particular.net/nservicebus/hosting/azure-functions-service-bus/isolated-worker
* https://docs.particular.net/samples/azure-functions/service-bus-worker/

If you're encountering issues or have suggestion, please raise them on the repository https://github.com/Particular/NServiceBus.AzureFunctions.Worker.ServiceBus

**Comment by timbussmann** [comment]
1.0 has been released - See the [release announcement](https://discuss.particular.net/t/nservicebus-azurefunctions-worker-servicebus-1-0-0-major-release-available/2575). Please raise feature requests or bug reports in the [NServiceBus.AzureFunctions.Worker.ServiceBus repository](https://github.com/Particular/NServiceBus.AzureFunctions.Worker.ServiceBus))
