### ISSUE TITLE
Release targeting NServiceBus version 8 - required assembly scanning changes

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureFunctions.InProcess.ServiceBus#159]
When released with NServiceBus version 8, the following changes need to be included:

1. Removal of the assembly scanning workaround fixed in Core v8.
2. Specification of the additional scanning path.
3. Ignoring of the thirst party assembly brought in by Functions in-process SDK into user project.
4. Document that assemblies found in both the Functions tooling folder and user Functions should be excluded by the NSB.Functions or customers can work-around it by using assembly exclusion API.

All changes are captured in PR https://github.com/Particular/NServiceBus.AzureFunctions.ServiceBus/pull/141.

**Comment by HEskandari** [comment]
Done via #266
