### ISSUE TITLE
Replace boilerplate function definition with dedicated source generator

### ISSUE THREAD

**Issue by tmasternak** [Particular/NServiceBus.AzureFunctions.InProcess.ServiceBus#209]
With .NET 5 [source generators](https://devblogs.microsoft.com/dotnet/introducing-c-source-generators/) it should be possible to remove boilerplate code that invokes [NServiceBus endpoint](https://docs.particular.net/nservicebus/hosting/azure-functions/service-bus#basic-usage-azure-function-definition) from Azure Function method body:

``` csharp
 [FunctionName("MyFunctionsEndpoint")]
    public async Task Run(
        [ServiceBusTrigger(queueName: "MyFunctionsEndpoint")]
        Message message,
        ILogger logger,
        ExecutionContext executionContext)
    {
        await endpoint.Process(message, executionContext, logger);
    }
```

**Comment by SeanFeldman** [comment]
> With .NET 5 source generators it should be possible to remove boilerplate code that invokes NServiceBus endpoint from Azure Function method body:

@tmasternak, removing `await endpoint.Process(message, executionContext, logger);` would still require some attribute to implement the generator. Isn't that the case, no?

And for the Function class, it would still require the constructor + member field(s) if there are dependencies other than the `IFunctionEndpoint ` injected, no?

**Comment by SeanFeldman** [comment]
\* Service Bus trigger function would not have any dependencies other than `IFunctionEndpoint` in the current design.

If C# Code Generator is used, it should be provided more value and generating the entire [Service Bus trigger function class](https://github.com/Particular/docs.particular.net/blob/a148a25bc24e786a4943aeef06f735496c6ef23b/samples/azure-functions/service-bus/ASBFunctions_1/AzureFunctions.ASBTrigger.FunctionsHostBuilder/AzureServiceBusTriggerFunction.cs#L7-L34) as that is usually the real boilerplate code.

```c#
public class AzureServiceBusTriggerFunction
{
    internal const string EndpointName = "ASBTriggerQueue";
    readonly IFunctionEndpoint endpoint;

    public AzureServiceBusTriggerFunction(IFunctionEndpoint endpoint)
    {
        this.endpoint = endpoint;
    }

    [FunctionName(EndpointName)]
    public async Task Run(
        [ServiceBusTrigger(queueName: EndpointName)]
        Message message,
        ILogger logger,
        ExecutionContext executionContext)
    {
        await endpoint.Process(message, executionContext, logger);
    }
}
```

This would require discovering the endpoint name by potentially decorating the `Startup` class and extracting the endpoint name from the code in the [endpoint configuration section](https://github.com/Particular/docs.particular.net/blob/a148a25bc24e786a4943aeef06f735496c6ef23b/samples/azure-functions/service-bus/ASBFunctions_1/AzureFunctions.ASBTrigger.FunctionsHostBuilder/Startup.cs#L27).

```c#
var configuration = new ServiceBusTriggeredEndpointConfiguration(AzureServiceBusTriggerFunction.EndpointName);
```

**Comment by tmasternak** [comment]
@SeanFeldman yep this makes sense. Users are not expected to change this part so if we generate it all the better off they are.

**Comment by SeanFeldman** [comment]
1.1.0 has been [released](https://discuss.particular.net/t/nservicebus-azurefunctions-inprocess-servicebus-1-1-0-minor-release-available/2477).
