### ISSUE TITLE
Add CancellationToken support to the Process method

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureFunctions.InProcess.ServiceBus#22]
Azure Functions [support `CancellationToken`](https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-class-library#cancellation-tokens) that should be accepted by NServiceBus.AzureFunctions.

Has dependency on NServiceBus Core [support for `CancellationToken`s](https://github.com/Particular/NServiceBus/issues/3785).

**Comment by timbussmann** [comment]
our pipeline doesn't really support cancellation tokens at the moment, so there isn't much to gain by passing this in besides maybe aborting the startup behavior. Not sure that's worth it for the noise it creates (and the expectations from the user).

**Comment by SeanFeldman** [comment]
This issue is here as a placeholder until Core has support for the cancellation token. It's not intended for public preview (Core v7).

**Comment by timbussmann** [comment]
I'm not sure it's desirable to keep placeholder issues open for features which aren't even scheduled at this point. We can always open this once this gets into the foreseeable timeline?
