### ISSUE TITLE
Connection string environment variable is required even if it is not used

### ISSUE THREAD

**Issue by mikeminutillo** [Particular/NServiceBus.AzureFunctions.InProcess.ServiceBus#232]
This package loads a connection string from an environment variable which by default is named `AzureWebJobsServiceBus` (but this can be overridden in the constructor for `ServiceBusTriggeredEndpointConfiguration`).

This is not the only way to set the transport connection. It can also be set like this:

```csharp
var endpointConfiguration = new ServiceBusTriggeredEndpointConfiguration("MyEndpoint");
endpointConfiguration.Transport.ConnectionString(myConnectionString);
```

Unfortunately this fails as the endpoint still attempts to load the connection string from an environment variable, even if there is one. [This code](https://github.com/Particular/NServiceBus.AzureFunctions.InProcess.ServiceBus/blob/master/src/NServiceBus.AzureFunctions.InProcess.ServiceBus/ServiceBusTriggeredEndpointConfiguration.cs#L50-L52) attempts to set the connection string to `null` which results in an exception:

> NServiceBus.Core: Value cannot be null. (Parameter 'connectionString').

## Workaround

To workaround this problem, a connection string must be available in the Azure Function environment variables and the `ServiceBusTriggeredEndpointConfiguration` should be configured to use this environment variable. Note that the connection string does not need to be for a valid ServiceBus account as it will not be used.

## Expected Behavior

It should be possible to set the connection string on the transport without setting an environment variable.

**Comment by SeanFeldman** [comment]
> It should be possible to set the connection string on the transport without setting an environment variable.

Does that mean the expected behaviour is not to have the environment variable `AzureWebJobsServiceBus` and solely use `endpointConfiguration.Transport.ConnectionString(myConnectionString);` to provide the connection string for NServiceBus endpoint?

**Comment by hardik-desai-kcl** [comment]
I think a second constructor with delegate as input parameter that allows configuring the EndpointConfiguration would be most appropriate solution 

At the moment the License and service bus connection string can only be supplied through convention and for both the assumption is that they are always going to be available in the environment variable 

But it is perfectly valid and possible that they may not be present in environment variables and it could be stored elsewhere i.e. in azure secure tables, keyvault, in local.settings.json during development or even some other secure storage and later retrieved through IConfiguration  

I think the simplest solution would be to have a new construct for ServiceBusTriggeredEndpointConfiguration that takes a delegate as parameter and allows consumers to do all their custom configuration for EndpointConfiguration before constructor method is executed 

Something like bellow, 

please note through there are few issues with bellow example 
the UseNServiceBus Method currently do not expose IServiceProvider so it would be ideal to have that available
ServiceBusTriggeredEndpointConfiguration uses internal implementation for Transport using ServerlessTransport class which is locked to internal only that would also need updating 


builder.UseNServiceBus((ServiceProvider) =>
{
    IConfiguration configuration = ServiceProvider.GetService<IConfiguration>();
    var servicebusConfig = new ServiceBusTriggeredEndpointConfiguration1(() =>
    {
        var endpointConfiguration = new EndpointConfiguration("EndpointName  from external source");
        endpointConfiguration.License("License FROM external source");
        var transportExtensions = endpointConfiguration.UseTransport<AzureServiceBusTransport>();
        transportExtensions.ConnectionString("Connection string from external source");
        return endpointConfiguration;
    });

    return servicebusConfig;
});

**Comment by SeanFeldman** [comment]
@hardik-desai-kcl could you please elaborate on the use case? Specifically, could you provide an answer to the question [here](https://github.com/Particular/NServiceBus.AzureFunctions.InProcess.ServiceBus/issues/232#issuecomment-884648351)? I'd like to understand what drives this request prior to discussing how to solution it. Thank you.

**Comment by hardik-desai-kcl** [comment]
so the issue we are having is that the NServicebus License and azure service bus connection string are not available through Environment variable in our azure function 

when I use ServiceBusTriggeredEndpointConfiguration to setup endpoint the only way to get the endpoint running is setting Environment variable AzureWebJobsServiceBus and NSERVICEBUS_LICENSE otherwise the ServiceBusTriggeredEndpointConfiguration constructor throws an exception

the expected behaviour is allow setting servicebus connection string and NSERVICEBUS_LICENSE

**Comment by SeanFeldman** [comment]
Thank you @hardik-desai-kcl.
The environment variable `AzureWebJobsServiceBus` is not NServiceBus environment variable but Azure Functions. The trigger will not work if it's not there unless you're planning to override it and specify the connection string **name** to the trigger function. Is that your intent?

**Comment by hardik-desai-kcl** [comment]
@SeanFeldman the AzureWebJobsServiceBus or a service connection string Name is only required if the Azure function had a service bus trigger function, even in the example here https://docs.particular.net/samples/azure-functions/service-bus/ there isn't any service bus trigger function and that is what our use case is, we want to build Azure function that has HTTP trigger and at the same time it hosts NSB endpoint and let NSB handle messages.

**Comment by SeanFeldman** [comment]
>  we want to build Azure function that has HTTP trigger and at the same time it hosts NSB endpoint and let NSB handle messages.

Thank you. That's all I needed to hear to understand the use case.
