### ISSUE TITLE
Dependency Injection Issue?

### ISSUE THREAD

**Issue by adamjones-lhpt** [Particular/NServiceBus.AzureFunctions.InProcess.ServiceBus#233]
VERSION: 1.2.0

It looks like dependency injection may not be working correctly in the latest version. After upgrading to version 1.2.0 and using the auto-generated function trigger my handlers are no longer having their properties set via dependency injection. 

Sample code:

```
[assembly: FunctionsStartup(typeof(Startup))]
[assembly: NServiceBusEndpointName(Startup.EndpointName, Startup.FunctionName)]

namespace LHPT.Backend.BizLogic.Maintenance.FunctionHost
{
	public class Startup : FunctionsStartup
	{
		public const string FunctionName = "bizlogicmaintenance";
		public const string EndpointName = "bizlogic.maintenance";
		private static IStatsDPublisher _StatsPublisher;

		public override void Configure(IFunctionsHostBuilder builder)
		{
			var statsConfiguration = new StatsDConfiguration()
			{
				Host = Environment.GetEnvironmentVariable("StatsdUrl"),
				Prefix = Environment.GetEnvironmentVariable("StatsdMetricsPrefix")
			};
			_StatsPublisher = new StatsDPublisher(statsConfiguration);

			builder.UseNServiceBus(() =>
			{
				var configuration = new ServiceBusTriggeredEndpointConfiguration(Startup.EndpointName);

				configuration.LogDiagnostics();

				configuration.AdvancedConfiguration.RegisterComponents(c =>
				{
					c.RegisterSingleton(_StatsPublisher);
				});
				return configuration;
			});
		}
	}
}
```

When the handlers are invoked my IStatsDPublisher property is null.

**Comment by SeanFeldman** [comment]
Release 1.2.0 did not change anything when it comes down to dependency injection and implements the trigger in exactly the same manner as 1.1.0

I've run through the [sample](https://docs.particular.net/samples/azure-functions/service-bus/) with a configuration similar to yours, using both NServiceBus component registration and the recommended `services.AddXXXX()` approaches and it works fine. @adamjones-lhpt, could you try the sample and see if you could reproduce the issue?

**Comment by adamjones-lhpt** [comment]
I got to the bottom of it. Our existing handlers rely on property injection. Property injection does not appear to be working. When I modify the handlers in the sample to have public properties exposing the dependent CustomComponent class, the property setter is never called prior to handler invocation. Sagas require a public parameterless constructor, but if I have both the public parameterless constructor as well as the constructor with our dependencies, the constructor with the dependencies is called.

It would be nice if we could still use property dependency injection, but I can work around this by updating our handlers and sagas.

**Comment by SeanFeldman** [comment]
Property injection is not supported with Microsoft container IIRC. You're better off with adopting constructor injection.
