### ISSUE TITLE
Release 2.0.2 does not use Azure.Messaging.ServiceBus for the incoming message

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureFunctions.InProcess.ServiceBus#340]
The [announced](https://discuss.particular.net/t/support-for-azure-messaging-servicebus-version-7-client-library-for-net/2771) 2.0.2 was supposed to use Azure Service Bus SDK version 7.x, but it doesn't do so end to end. Only the NServiceBus transport for Azure Service Bus uses the stated package `Azure.Messaging.ServiceBus`, the function trigger is still on the older SDK, `Microsoft.Azure.ServiceBus`. This is causing a problem due to the features found in `Azure.Messaging.ServiceBus` not being available in the older `Microsoft.Azure.ServiceBus`. For more details, see my comment at the Discourse [thread](https://discuss.particular.net/t/support-for-azure-messaging-servicebus-version-7-client-library-for-net/2771/4).

**Comment by WilliamBZA** [comment]
Fix has been merged, we're now waiting for MS to release a version which exposes the `ServiceBusClient` instance. Will revisit once released.

**Comment by cquirosj** [comment]
[Microsoft.Azure.WebJobs.Extensions.ServiceBus_5.1.0](https://github.com/Azure/azure-sdk-for-net/releases/tag/Microsoft.Azure.WebJobs.Extensions.ServiceBus_5.1.0) has been released. This work can be completed during the next azure enhancement release.

**Comment by andreasohlund** [comment]
https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.ServiceBus/5.2.0 is out now as well

**Comment by andreasohlund** [comment]
This will be fixed in the upcoming v3.0.0 https://github.com/Particular/NServiceBus.AzureFunctions.InProcess.ServiceBus/pull/396
