### ISSUE TITLE
Calling UseTransport<> explicitly causes a NullReferenceException in Process

### ISSUE THREAD

**Issue by mikeminutillo** [Particular/NServiceBus.AzureFunctions.InProcess.ServiceBus#377]
A user should not have to `UseTransport<>` in their configuration as the package does it for them. If they do call `UseTransport<>` anyway then a `NullReferenceException` occurs when any of the `Process` methods are called on the endpoint.

## Steps to reproduce

- Create a new Azure Function project
- In the call to `UseNServiceBus(...)` include `configuration.AdvancedConfiguration.UseTransport<AzureServiceBusTransport>()`
- Start the function and call `Process` on the endpoint. A `NullReferenceException` is thrown.

## Root cause

This is happening because the call to `UseTransport<>` needs to be intercepted to prevent the message receive infrastructure from starting and capture the receive pipeline for use inside of `Process` messages. When a customer calls `UseTransport<>` this interception does not happen, and `Process` attempts to push the message to a null receive pipeline.

Unfortunately, we cannot prevent someone from calling `UseTransport<>` without taking away all of the other advanced configuration APIs. We might consider detecting at startup if the transport has been properly intercepted and throwing an exception if it has not. Alternatively, we can test the receive pipeline in `Process` and throw a more meaningful exception if it is null.

**Comment by ramonsmits** [comment]
Another user ran into this.

**Comment by DavidBoike** [comment]
Fixed by https://github.com/Particular/NServiceBus.AzureFunctions.InProcess.ServiceBus/issues/615, will be released in 4.2.0.
