### ISSUE TITLE
Remove assembly scanning and loading workaround for NServiceBus v8

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureFunctions.InProcess.ServiceBus#49]
When NServiceBus Core implements a fix for https://github.com/Particular/NServiceBus/issues/5662, the workaround implemented in NServiceBus.AzureFunctions can be safely removed.

Function assembly path for scanning can be provided via [Core's new API](https://github.com/Particular/NServiceBus/pull/5653)

**Comment by HEskandari** [comment]
Done via #266
