### ISSUE TITLE
Handle `UseTransport` gracefully

### ISSUE THREAD

**Issue by mikeminutillo** [Particular/NServiceBus.AzureFunctions.InProcess.ServiceBus#615]
You should not have to call `UseTransport`, as the library does it for you and makes the transport (and routing) available on `ServiceBusTriggeredEndpointConfiguration`.

If you do call `UseTransport` the library should handle it gracefully.

Prior to this change, calling `UseTransport` was unsupported and [caused unpredictable behavior](https://github.com/Particular/NServiceBus.AzureFunctions.InProcess.ServiceBus/issues/377)

**Comment by SzymonPobiega** [comment]
Completed in https://github.com/Particular/NServiceBus.AzureFunctions.InProcess.ServiceBus/pull/614, awaiting release.

**Comment by DavidBoike** [comment]
Will be released in 4.2.0 today or tomorrow.

**Comment by ramonsmits** [comment]
@mikeminutillo What does "If you do call UseTransport the library should handle it gracefully." will it now throw a exception like `InvalidOperationException` or `NotSupportedException` with details that UseTransport is not supported in the context of azure functions?

**Comment by mikeminutillo** [comment]
@ramonsmits the associated PR is here https://github.com/Particular/NServiceBus.AzureFunctions.InProcess.ServiceBus/pull/614

It defers setting up the infrastructure until _after_ the user configuration has been applied. That way, if the transport has been changed with `UseTransport` the serverless infrastructure will be set up around the configured transport instead of the default one we implement.
