### ISSUE TITLE
Using SendOnly throws a KeyNotFoundException with Main as a key

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus.AzureFunctions.InProcess.ServiceBus#617]
Copy of https://github.com/Particular/NServiceBus.AzureFunctions.Worker.ServiceBus/issues/220 for the in-process hosting model which has the same issue

## Workaround

An endpoint can be operated in send-only mode using these steps:
1. Do not use the endpoint `SendOnly()` configuration
2. Remove the `NServiceBusTriggerFunction` attribute
3. Use NServiceBus.Transport.AzureServiceBus 3.1.3 or higher

**Comment by SeanFeldman** [comment]
Anyone's trying to run a send-only endpoint, here are more detailed workaround steps that worked:

1. Do not use the endpoint `SendOnly()` configuration in `.UseNServiceBus()` callback.
2. Remove the `NServiceBusTriggerFunction` attribute from `FunctionsStartup` implementing class.
3. Use `UseNServiceBus(string endpointName, Action<ServiceBusTriggeredEndpointConfiguration> configurationFactory)` overload.
4. Use NServiceBus.Transport.AzureServiceBus 3.1.3 or higher

**Comment by SeanFeldman** [comment]
@timbussmann, there's no milestone associated with this issue. It's already addressed in the PR #714, which also doesn't have a milestone. Is this going to be in the next release,  4.2.1 or 4.3.0?

**Comment by jpalac** [comment]
@SeanFeldman we have now created [4.3.0 milestone](https://github.com/Particular/NServiceBus.AzureFunctions.InProcess.ServiceBus/milestone/24) for these changes - they will be released soon.

**Comment by mikeminutillo** [comment]
@SeanFeldman we have just released 4.3.0, which includes this change. Please let us know if it causes any issues.

**Comment by SeanFeldman** [comment]
Thank you, @mikeminutillo and @jpalac
